version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "${PORT:-5000}:4000"
    environment:
      PORT: 4000
      PHX_HOST: localhost
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      UMAMI_TRACKING_ENABLED: "true"
      UMAMI_BASE_URL: http://analytics:3000
      UMAMI_WEBSITE_ID: ${UMAMI_WEBSITE_ID}

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      # POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_NAME},${DATABASE_NAME}_umami

  analytics:
    image: ghcr.io/umami-software/umami:postgresql-v1.40.0
    restart: always
    ports:
      - "3000:3000"
    environment:
      REMOVE_TRAILING_SLASH: 1
      DATABASE_TYPE: postgresql
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}_umami
      HASH_SALT: VEcOyzBVFsxNN1PMJuaDXTbN5VxRxoAAHYLuIR2kwPHNmP9PAcX/RwAGqRfjTRhL
      CLIENT_IP_HEADER: "umami-client-ip"

volumes:
  postgres-data:
